jenkins:
  systemMessage: "Jenkins auto-config via JCasC"
  numExecutors: 2

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  globalNodeProperties:
    - envVars:
        env:
          - key: "NVD_API_KEY"
            value: "${NVD_API_KEY}"

unclassified:
  location:
    adminAddress: "admin@example.com"
    url: "http://jenkins:8080/"

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              id: "github-token"
              description: "GitHub Token"
              secret: "${GITHUB_TOKEN}"
          - string:
              id: "SONAR_TOKEN"
              description: "SonarQube Token"
              secret: "${SONAR_TOKEN}"

jobs:
  - script: >
      pipelineJob('nextjs-ci') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/Dr4kiel/Management-Qualite-TP.git')
                 }
                    branches('*/main', '*/develop')
                 }
            }
            scriptPath('Jenkinsfile')
          }
          triggers {
            scm('H/5 * * * *')
            githubPush()
          }
        }
      }

tool:
  dependency-check:
    installations:
    - name: "Default"
      properties:
      - installSource:
          installers:
          - dependencyCheckInstaller:
              id: "12.1.3"
              
  sonarRunnerInstallation:
    installations:
    - name: "Default"
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "7.1.0.4889"